version: '3.7'

volumes:
  api_resume_data:
    driver: local

services:
  api_nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    depends_on:
      - api_php
    volumes:
    - ./public:/api/public
    ports:
      - 80:80
    restart: always

  api_php:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    volumes:
      - .:/api
    depends_on:
      - postgres
    restart: always

  postgres:
    build:
      args:
        VERSION: $POSTGRES_VERSION
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - api_resume_data:/var/lib/postgresql/data
    restart: always
