name: Test

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  test_php:
    name: Run PHPUnit unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Download PHP test env artifact
        uses: actions/download-artifact@v2
        with:
          name: api_php-test

      - name: Run tests
        run: docker run --rm api_php:test bin/phpunit --testdox
